// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	orderedmapjson "github.com/GitRowin/orderedmapjson"
	mock "github.com/stretchr/testify/mock"
)

// RecordSender is an autogenerated mock type for the RecordSender type
type RecordSender struct {
	mock.Mock
}

// SendRecord provides a mock function with given fields: _a0
func (_m *RecordSender) SendRecord(_a0 *orderedmapjson.AnyOrderedMap) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*orderedmapjson.AnyOrderedMap) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecordSender creates a new instance of RecordSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecordSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecordSender {
	mock := &RecordSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
